filetype plugin indent on

syntax on

let line='normal'

set rtp+=~/.fzf

set nocompatible
set number
set expandtab
set sts=2 sw=2 ts=2
set colorcolumn=81
set hls
set incsearch
set ignorecase
set fileencodings=utf-8,gb2312,gbk,gb18030
set foldcolumn=4
set foldenable
set foldlevel=100
set foldmethod=marker
set showcmd
set mouse=a
set selection=exclusive
set selectmode=mouse,key
set title
set backupcopy=yes
set backspace=indent,eol,start
set clipboard=unnamed
set autochdir
set autoindent
set nobackup
set pastetoggle=``
set shortmess=atl
set ttyfast

highlight ColorColumn ctermbg=gray

:command W w
:command WQ wq
:command Wq wq
:command Q q

