export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="ys"
plugins=(
    git
    zsh-autosuggestions
    zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh
unsetopt nomatch

alias pp='fzf --preview '"'"'[[ $(file --mime {}) =~ binary ]] && echo {} is a binary file || (rougify {}  || highlight -O ansi -l {} || coderay {} || cat {}) 2> /dev/null | head -500'"'"

# git alias
alias gt='git'
alias gi='git'
alias gti='git'
alias ga='git add'
alias gs='git status'
alias gd='git diff'
alias gc='git commit'
alias gg='git log --all --decorate --oneline --graph'
alias gpush='git push'
alias gpull='git pull'
alias gaa='git add *'

# ls alias
alias s='ls'
alias sl='ls'
alias a='ls -a'
alias la='ls -a'
alias ll='ls -l'
alias al='ls -al'
alias lla='ls -la'
alias lal='ls -al'

# tmux alias
alias tl='tmux ls'
alias ts='tmux ls'
alias ta='tmux a -t'
alias ts='tmux new -s'
alias tn='tmux new'

# other alias
alias c='cd'
alias t='tree'
alias h='htop'
alias g='gtop'
alias e='echo'
alias w='which'
alias d='df -hT'
